version: "3"
services:
  clinwiki:
    image: keymetrics/pm2:14-alpine
    container_name: clinwiki-notify
    volumes:
      - type: bind
        source: ./
        target: /clinwiki-notify
      - type: volume
        source: node_modules # name of the volume, see below
        target: /clinwiki-notify/node_modules
        volume:
          nocopy: true
    working_dir: /clinwiki-notify
    command: npm run dev
volumes:
  node_modules:
