version: "3.4"
services:
  clinwiki:
    image: keymetrics/pm2:14-alpine
    container_name: clinwiki-notify
    network_mode: host
    volumes:
      - type: bind
        source: ./
        target: /clinwiki-notify
      - type: volume
        source: nodemodules # name of the volume, see below
        target: /clinwiki-notify/node_modules
        volume:
          nocopy: true
    working_dir: /clinwiki-notify
    command: npm run dev
volumes:
  nodemodules:

